.PHONY: clean All

All:
	@echo "----------Building project:[ VirtualFunctionNew - Debug ]----------"
	@cd "VirtualFunctionNew" && "$(MAKE)" -f  "VirtualFunctionNew.mk"
clean:
	@echo "----------Cleaning project:[ VirtualFunctionNew - Debug ]----------"
	@cd "VirtualFunctionNew" && "$(MAKE)" -f  "VirtualFunctionNew.mk" clean
